// Generated by CoffeeScript 1.6.2
var $;

$ = jQuery;

$(function() {
  var editor;

  jQuery.event.props.push('dataTransfer');
  $(document).on('dragover drop', function(e) {
    return e.preventDefault();
  });
  $('#testimg').on('dragstart', function(e) {
    return e.dataTransfer.setData('text/html', null);
  });
  $('#testarea').on('dragover', function(e) {
    return console.log(e);
  });
  JJMarkdownEditor.setAsDraggable($('#testimg'));
  return editor = new JJMarkdownEditor('#editor', {
    afterRender: function() {
      return window.picturefill();
    },
    onChange: function(data) {
      return console.log(data);
    }
  });
});
