// Generated by CoffeeScript 1.6.2
var $;

$ = jQuery;

$(function() {
  var editor;

  jQuery.event.props.push('dataTransfer');
  $(document).on('dragover drop', function(e) {
    return e.preventDefault();
  });
  $('#testarea').on('dragover', function(e) {
    return console.log(e);
  });
  JJMarkdownEditor.setAsDraggable($('#testimg'));
  editor = new JJMarkdownEditor('#editor', {
    afterRender: function() {
      return window.picturefill();
    }
  });
  return new JJImageDropzone('#dropper', {
    url: '/_md_/images/personimage'
  });
});
