// Generated by CoffeeScript 1.6.2
(function() {
  var $;

  $ = jQuery;

  $(function() {
    var editor;

    jQuery.event.props.push('dataTransfer');
    $(document).on('dragover drop', function(e) {
      return e.preventDefault();
    });
    return editor = new JJMarkdownEditor('#editor');
  });

}).call(this);
