// Generated by CoffeeScript 1.4.0

define(["jquery", "underscore", "backbone", "handlebars", "plugins/backbone.layoutmanager"], function($, _, Backbone, Handlebars) {
  var JST, app;
  app = {
    root: '/'
  };
  JST = window.JST = window.JST || {};
  Backbone.LayoutManager.configure({
    manage: true,
    paths: {
      layout: 'app/templates/layouts/',
      template: 'app/templates/'
    },
    fetch: function(path) {
      var done;
      done = void 0;
      path = path + '.html';
      if (!JST[path]) {
        done = this.async();
        return $.ajax({
          url: app.root + path
        }).then(function(contents) {
          JST[path] = Handlebars.compile(contents);
          JST[path].__compiled__ = true;
          return done(JST[path]);
        });
      }
      if (!JST[path].__compiled__) {
        JST[path] = Handlebars.template(JST[path]);
        JST[path].__compiled__ = true;
      }
      return JST[path];
    }
  });
  return _.extend(app, {
    module: function(additionalProps) {
      return _.extend({
        Views: {}
      }, additionalProps);
    },
    useLayout: function(name, options) {
      var layout;
      if (this.layout && this.layout.options.template === name) {
        return this.layout;
      }
      if (this.layout) {
        this.layout.remove();
      }
      layout = new Backbone.Layout(_.extend({
        template: name,
        className: "layout " + name,
        id: "layout"
      }, options));
      $("#main").empty().append(layout.el);
      layout.render();
      this.layout = layout;
      return layout;
    }
  }, Backbone.Events);
});
