// Generated by CoffeeScript 1.4.0

require.config({
  deps: ['main'],
  paths: {
    libs: '../assets/js/libs',
    plugins: '../assets/js/plugins',
    jquery: '../assets/js/libs/jquery',
    underscore: '../assets/js/libs/underscore',
    backbone: '../assets/js/libs/backbone',
    handlebars: '../assets/js/libs/handlebars'
  },
  shim: {
    backbone: {
      deps: ['underscore', 'jquery'],
      exports: 'Backbone'
    },
    underscore: {
      exports: '_'
    },
    handlebars: {
      exports: 'Handlebars'
    },
    'plugins/backbone.layoutmanager': ['backbone']
  }
});
