// Generated by CoffeeScript 1.6.2
require(['app', 'router', 'modules/example', 'modules/Project', 'modules/Person'], function(app, Router, Example, Project, Person) {
  app.Router = new Router();
  app.Layouts = {};
  app.PageInfos = {};
  app.Collections = {};
  $(function() {
    return JJRestApi.bootstrapWithStructure(function() {
      var PersonCollection, ProjectCollection;

      ProjectCollection = JJRestApi.Collection('Project');
      PersonCollection = JJRestApi.Collection('Person');
      app.Collections.Projects = new ProjectCollection();
      app.Collections.Persons = new PersonCollection();
      app.Layouts.Main = app.useLayout('main', {
        views: {
          '': []
        }
      });
      return Backbone.history.start({
        pushState: true
      });
    });
  });
  return $(document).on('click', 'a:not([data-bypass])', function(evt) {
    var href, protocol;

    href = $(this).attr('href');
    protocol = this.protocol + '//';
    if (href && href.slice(0, protocol.length) !== protocol && href.indexOf('javascript:') !== 0) {
      evt.preventDefault();
      return Backbone.history.navigate(href, true);
    }
  });
});
