// Generated by CoffeeScript 1.6.2
require(['app', 'router', 'modules/Project', 'modules/Person', 'modules/Excursion', 'modules/Workshop', 'modules/Exhibition', 'modules/CalendarEntry'], function(app, Router, Project, Person, Excursion, Workshop, Exhibition, CalendarEntry) {
  Backbone.JJRelational.Config.work_with_store = true;
  app.Router = new Router();
  app.Layout;
  app.PageInfos = {};
  app.Collections = {};
  app.Config = {
    ProjectTypes: ['Project', 'Excursion', 'Workshop', 'Exhibition'],
    StoreHooks: ['Project', 'Excursion', 'Workshop', 'Exhibition', 'Person', 'CalendarEntry'],
    UrlSuffixes: {
      about_persons: '?search=IsExternal:0'
    },
    Featured: {
      present: {
        flag: false,
        types: []
      },
      domName: function(className) {
        return 'featured-' + className.toLowerCase();
      },
      urlSuffix: '?' + JJRestApi.objToUrlString({
        search: {
          IsFeatured: 1
        },
        context: 'view.portfolio_init'
      })
    },
    Portfolio: {
      present: {
        flag: false,
        types: []
      },
      domName: function(className) {
        return 'portfolio-' + className.toLowerCase();
      },
      urlSuffix: '?' + JJRestApi.objToUrlString({
        search: {
          IsPortfolio: 1
        },
        context: 'view.portfolio_init'
      })
    },
    Calendar: {
      upcoming: {
        flag: false,
        url: 'api/v2/UpcomingEvents.json'
      },
      whole: {
        flag: false
      }
    },
    Person: {
      about_present: false
    },
    Detail: {
      CalendarEntry: {
        where: function(slug) {
          return {
            UrlHash: slug
          };
        },
        domName: 'detailed-calendar-item',
        urlSuffix: function(slug) {
          return '?' + JJRestApi.objToUrlString({
            search: {
              UrlHash: slug
            }
          });
        }
      }
    }
  };
  app.bindListeners = function() {
    var storeHook, _fn, _i, _len, _ref;

    _ref = app.Config.StoreHooks;
    _fn = function(storeHook) {
      return Backbone.JJStore.Events.bind('added:' + storeHook, function(model) {
        var coll;

        coll = app.Collections[storeHook];
        if (coll) {
          return coll.add(model);
        }
      });
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      storeHook = _ref[_i];
      _fn(storeHook);
    }
    return true;
  };
  app.handleFetchedModels = function(type, data, options) {
    var MType, d, _i, _len, _results;

    options = options || {};
    MType = JJRestApi.Model(type);
    data = _.isArray(data) ? data : [data];
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      d = data[_i];
      _results.push(new MType(d));
    }
    return _results;
  };
  app.handleFetchedModel = function(type, data, options) {
    var MType;

    options = options || {};
    MType = JJRestApi.Model(type);
    return new MType(data);
  };
  app.bindListeners();
  $(function() {
    return JJRestApi.bootstrapWithStructure(function() {
      var buildCollections;

      buildCollections = function(names) {
        var CollClass, name, _i, _len, _results;

        _results = [];
        for (_i = 0, _len = names.length; _i < _len; _i++) {
          name = names[_i];
          CollClass = JJRestApi.Collection(name);
          _results.push(app.Collections[name] = new CollClass());
        }
        return _results;
      };
      buildCollections(app.Config.StoreHooks);
      return Backbone.history.start({
        pushState: true
      });
    });
  });
  return $(document).on('click', 'a:not([data-bypass])', function(evt) {
    var href, protocol;

    href = $(this).attr('href');
    protocol = this.protocol + '//';
    if (href && href.slice(0, protocol.length) !== protocol && href.indexOf('javascript:') !== 0) {
      evt.preventDefault();
      return Backbone.history.navigate(href, true);
    }
  });
});
