// Generated by CoffeeScript 1.6.2
"use strict";(function($) {
  return $('.gravity').RadialGravity({
    worker: {
      physics: './js/gravity/physics.js'
    }
  });
  /*
  	$('.gravity').RadialGravity 'add',
  		id: 'foobar'
  		width: 200,
  		height: 200,
  		top: 0,
  		left: 0
  */

})(Zepto);
