// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

(function($, window) {
  var Box2DHolder, Entity, GravityCenter, RadialGravityStorage, RectangleEntity, _ref;

  window.requestAnimFrame = (function() {
    return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback, element) {
      return window.setTimeout(callback, 1000 / 60);
    };
  })();
  if (Deferred) {
    Deferred.installInto(Zepto);
  }
  /*
  	 # Creates a basic Entity with the given parameters
  	 # this should be just the base class to extend.
  	 #
  	 # @param int id
  	 # @param float x
  	 # @param float y
  	 # @param float angle (optional)
  */

  Entity = (function() {
    function Entity(id, x, y, angle) {
      this.id = id;
      this.x = x;
      this.y = y;
      this.angle = angle != null ? angle : 0;
    }

    Entity.prototype.update = function(x, y, angle) {
      this.x = x;
      this.y = y;
      this.angle = angle;
    };

    Entity.prototype.setAwake = function(isAwake) {
      this.isAwake = isAwake;
    };

    Entity.prototype.scale = function() {
      return window.BOX2D_SCALE || 30;
    };

    Entity.prototype.draw = function() {};

    return Entity;

  })();
  /*
  	 # Creates a Rectangle with the given parameters
  	 #
  	 # @param int id
  	 # @param float x
  	 # @param float y
  	 # @param float width
  	 # @param float height
  	 # @param float angle (optional)
  */

  RectangleEntity = (function(_super) {
    __extends(RectangleEntity, _super);

    RectangleEntity.prototype.color = 'red';

    RectangleEntity.prototype.sleepColor = 'gray';

    function RectangleEntity(id, x, y, width, height, angle) {
      this.id = id;
      this.x = x;
      this.y = y;
      this.width = width != null ? width : 0;
      this.height = height != null ? height : 0;
      this.angle = angle != null ? angle : 0;
      /*
      			$item = $("[data-gravity-item=#{@id}]")
      
      			if not $item.length
      				$('<div class="entity" data-gravity-item="' + @id + '">' + @id + '</div>')
      					.appendTo('.gravity')
      */

      RectangleEntity.__super__.constructor.call(this, this.id, this.x, this.y, this.angle);
    }

    RectangleEntity.prototype.halfWidth = function() {
      return this.width / 2;
    };

    RectangleEntity.prototype.halfHeight = function() {
      return this.height / 2;
    };

    RectangleEntity.prototype.draw = function() {
      return $("[data-gravity-item=" + this.id + "]").css({
        'top': this.y * this.scale(),
        'left': this.x * this.scale(),
        'margin-top': -this.height * this.scale() / 2,
        'margin-left': -this.width * this.scale() / 2,
        'height': this.height * this.scale(),
        'width': this.width * this.scale(),
        'background': this.isAwake ? this.color : this.sleepColor
      });
    };

    return RectangleEntity;

  })(Entity);
  GravityCenter = (function(_super) {
    __extends(GravityCenter, _super);

    function GravityCenter() {
      _ref = GravityCenter.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    GravityCenter.prototype.color = 'green';

    GravityCenter.prototype.draw = function() {};

    return GravityCenter;

  })(RectangleEntity);
  Box2DHolder = (function() {
    Box2DHolder.prototype.useWorker = false;

    Box2DHolder.prototype.worker = null;

    Box2DHolder.prototype.bodiesState = {};

    Box2DHolder.prototype.world = {};

    Box2DHolder.prototype.border = {};

    Box2DHolder.prototype.box = null;

    Box2DHolder.prototype.msgID = 0;

    Box2DHolder.prototype.needToDraw = true;

    Box2DHolder.prototype.scaleFactor = 30;

    Box2DHolder.prototype.setScale = function(val) {
      this.scaleFactor = val;
      if (this.worker) {
        return this.worker.postMessage({
          key: 'setscale',
          value: val
        });
      }
    };

    /*
    		 # constructs the Box2DHolder
    		 #
    		 # @param int width
    		 # @param int height
    */


    function Box2DHolder(width, height, zoom, workerOpts) {
      this.width = width;
      this.height = height;
      this.zoom = zoom;
      this.workerOpts = workerOpts;
      this.loop = __bind(this.loop, this);
      this.init = function() {
        var _this = this;

        console.log('Box2DHolder init');
        this.useWorker = this.hasWebWorker();
        document.addEventListener('webkitvisibilitychange', (function() {
          if (document.webkitHidden) {
            return _this.stop();
          } else {
            return _this.start();
          }
        }), false);
        this.initResize();
        if (this.useWorker) {
          this.initWorker();
        } else {
          this.initNonWorker();
        }
        return this.loop();
      };
      this.initResize = function() {
        var _this = this;

        this.resizeTimeoutId;
        return window.onresize = function(event) {
          clearTimeout(_this.resizeTimeoutId);
          return _this.resizeTimeoutId = window.setTimeout(function() {
            _this.width = window.innerWidth || document.documentElement.clientWidth;
            _this.height = window.innerHeight || document.documentElement.clientHeight;
            if (_this.worker) {
              _this.worker.postMessage({
                key: 'dimensions',
                width: _this.n(_this.width),
                height: _this.n(_this.height)
              });
              return _this.needToDraw = true;
            }
          }, 10);
        };
      };
      /*
      			 # Returns whether the page supports web workers
      */

      this.hasWebWorker = function() {
        return typeof Worker !== 'undefined';
      };
      /*
      			 # creates the worker and sends the entities down the wire
      */

      this.initWorker = function() {
        var _this = this;

        this.worker = new Worker(this.workerOpts.physics);
        this.worker.onmessage = function(e) {
          var id, newBodies, newBody, _results;

          if ('log' === e.data.key) {
            console.info('physics log:');
            console.log(e.data.log);
            return;
          }
          newBodies = e.data.bodiesState;
          _this.bodiesState = $.extend({}, _this.bodiesState, newBodies);
          console.log(Object.keys(_this.bodiesState).length);
          /*
          					if not @bodiesState
          						@bodiesState = newBodies
          						@needToDraw = true
          					else
          */

          _results = [];
          for (id in _this.bodiesState) {
            newBody = newBodies[id];
            if (_this.world[id]) {
              if (newBody) {
                _this.world[id].setAwake(true);
                _this.bodiesState[id] = newBody;
                _results.push(_this.needToDraw = true);
              } else if (_this.world[id].isAwake) {
                _this.needToDraw = true;
                _results.push(_this.world[id].setAwake(fals));
              } else {
                _results.push(void 0);
              }
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        };
        this.worker.postMessage({
          key: 'dimensions',
          width: this.n(this.width),
          height: this.n(this.height)
        });
        console.log('sent dimensions %i, %i');
        console.log(this.n(this.width));
        console.log(this.height);
        return console.log(this.n(this.height));
      };
      /*
      			 # creates the worker fallback
      */

      this.initNonWorker = function() {
        alert('no webworker support :(');
        return console.log('init non worker');
      };
      /*
      			 # creates dummy entities
      */

      this.createDummies = function(amount) {
        var entity, i, x, y, _results;

        if (amount == null) {
          amount = 20;
        }
        i = 0;
        _results = [];
        while (i < amount) {
          x = Math.random() * 50;
          y = Math.random() * 20;
          entity = new RectangleEntity("entity_" + i, x, y, Math.random() + 0.4, Math.random() + 0.4);
          this.addEntity(entity);
          _results.push(i++);
        }
        return _results;
      };
      this.init();
    }

    /*
    		 # public add
    */


    Box2DHolder.prototype.add = function(obj) {
      var entity, gravity;

      if (obj.id === 'gravity') {
        gravity = new GravityCenter(obj.id, this.n(obj.left), this.n(obj.top));
        return this.addGravity(gravity);
      } else if (obj.width && obj.height) {
        entity = new RectangleEntity(obj.id, this.n(obj.left), this.n(obj.top), this.n(obj.width), this.n(obj.height));
        return this.addEntity(entity);
      }
    };

    /*
    		 # n pixel to float values
    */


    Box2DHolder.prototype.n = function(num) {
      return num / this.scaleFactor;
    };

    /*
    		 # running thread
    */


    Box2DHolder.prototype.looper = 0;

    Box2DHolder.prototype.loop = function(animStart) {
      this.update(animStart);
      this.draw();
      return window.requestAnimFrame(this.loop);
    };

    /*
    		 # (re)-starts the simulation
    */


    Box2DHolder.prototype.start = function() {
      return this.worker.postMessage({
        key: 'start'
      });
    };

    /*
    		 # stops the simulation
    */


    Box2DHolder.prototype.stop = function() {
      return this.worker.postMessage({
        key: 'stop'
      });
    };

    /*
    */


    Box2DHolder.prototype.addGravity = function(gravity) {
      return this.worker.postMessage({
        key: 'addEntity',
        entity: gravity
      });
    };

    /*
    */


    Box2DHolder.prototype.addEntity = function(entity) {
      console.log("added entity '" + entity.id + "'");
      this.world[entity.id] = entity;
      console.log(this.world);
      return this.worker.postMessage({
        key: 'addEntity',
        entity: this.world[entity.id]
      });
    };

    /*
    		 # triggers the update
    		 # uses the worker if possible and sends him a message down the pipe
    		 #
    */


    Box2DHolder.prototype.update = function(animStart) {
      var entity, id, state, _results;

      if (this.useWorker) {
        if (this.needToDraw) {
          this.worker.postMessage({
            key: 'req',
            id: this.msgID
          });
          this.msgID++;
        }
      } else {
        this.box.update();
        this.bodiesState = this.box.getState();
        this.needToDraw = true;
      }
      _results = [];
      for (id in this.bodiesState) {
        entity = this.world[id];
        state = this.bodiesState[id];
        if (entity) {
          _results.push(entity.update(state.x, state.y, state.a));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    /*
    		 # redraws the world entities if nessessary
    		 #
    		 # @use this.needToDraw
    */


    Box2DHolder.prototype.draw = function() {
      var entity, id, _ref1;

      if (!this.needToDraw) {
        return;
      }
      _ref1 = this.world;
      for (id in _ref1) {
        entity = _ref1[id];
        entity = this.world[id];
        entity.draw();
      }
      return this.needToDraw = false;
    };

    return Box2DHolder;

  })();
  RadialGravityStorage = {
    itemIdCount: 0,
    implementationCount: 0,
    implementations: {}
  };
  window.Storage = RadialGravityStorage;
  return $.extend($.fn, {
    RadialGravity: function(methodOrOptions) {
      var dataIdName, methods, self, storage;

      this.defaultOptions = {
        box2dZoom: 5,
        elementSelector: null,
        itemIdPrefix: 'gravity-item-',
        box2d: {
          scale: 100
        },
        worker: {
          physics: 'physics.js'
        }
      };
      dataIdName = 'gravity-id';
      self = this;
      storage = function(count) {
        return RadialGravityStorage.implementations[count];
      };
      methods = {
        init: function(options) {
          var getCountId, opts,
            _this = this;

          opts = $.extend({}, this.defaultOptions, options);
          getCountId = function() {
            RadialGravityStorage.itemIdCount++;
            return RadialGravityStorage.itemIdCount;
          };
          return this.each(function(i, el) {
            var addGravity, findItems, getItemId, getStorageId, init, initResize, layoutItems, resizeTimeoutId, storageId;

            storageId = RadialGravityStorage.implementationCount;
            RadialGravityStorage.implementationCount++;
            RadialGravityStorage.implementations[storageId] = {
              $container: null,
              box2DHolder: null,
              width: 0,
              height: 0,
              options: opts
            };
            storage = function() {
              return RadialGravityStorage.implementations[storageId];
            };
            init = function() {
              storage().$container = $(el).data(dataIdName, storageId);
              storage().width = storage().$container.width();
              storage().height = storage().$container.height();
              if (storage().height <= 0) {
                storage().height = $(window).height();
              }
              console.log(storage().width);
              console.log(storage().height);
              storage().box2DHolder = new Box2DHolder(storage().width, storage().height, opts.box2dZoom, opts.worker);
              storage().box2DHolder.setScale(opts.box2d.scale);
              window.BOX2D_SCALE = opts.box2d.scale;
              initResize();
              addGravity();
              return findItems();
            };
            resizeTimeoutId = null;
            initResize = function() {
              var _this = this;

              return window.onresize = function(event) {
                clearTimeout(resizeTimeoutId);
                return resizeTimeoutId = setTimeout(function() {
                  console.log('on resize');
                  return addGravity();
                }, 10);
              };
            };
            getStorageId = function() {
              return opts.itemIdPrefix + ("" + storageId + "-");
            };
            getItemId = function() {
              return getStorageId() + getCountId();
            };
            addGravity = function() {
              return methods.add({
                id: 'gravity',
                top: storage().height / 2,
                left: storage().width / 2
              }, storageId);
            };
            layoutItems = function($items) {
              /*
              						elems = document.getElementsByTagName('div');
              						increase = Math.PI * 2 / elems.length;
              
              						var x = 0, y = 0, angle = 0, elem;
              
              						for (var i = 0; i < elems.length; i++) {
              							elem = elems[i];
              							x = 100 * Math.cos(angle) + 200;
              							y = 100 * Math.sin(angle) + 200;
              							elem.style.position = 'absolute';
              							elem.style.left = x + 'px';
              							elem.style.top = y + 'px';
              							angle += increase;
              						}
              */

            };
            findItems = function() {
              var $items,
                _this = this;

              $items = opts.elementSelector ? storage().$container.find(opts.elementSelector) : storage().$container.children();
              return $.each($items, function(index, item) {
                var $item, itemData, itemId, pos;

                $item = $(item);
                pos = $item.position();
                itemId = getItemId();
                itemData = {
                  id: itemId,
                  width: $item.width(),
                  height: $item.height(),
                  top: pos.top,
                  left: pos.left
                };
                console.log($item);
                $item.data('gravity-item', itemId);
                return methods.add(itemData, storageId);
              });
            };
            init();
            return true;
          });
        },
        show: function() {},
        hide: function() {},
        update: function(content) {},
        /*
        			 # adds an item to the gravity world
        			 #
        			 # @param object data
        			 #
        			 # @example
        			 # 		$('selector').RadialGravity('add', {
        			 #			id: 'foobar',
        			 #			width: 100,
        			 #			height: 100,
        			 #			top: 0,
        			 #			left: 0
        			 #		});
        */

        add: function(data, implementationCount) {
          if (implementationCount === void 0) {
            implementationCount = $(this).data(dataIdName);
          } else if (typeof implementationCount !== 'number') {
            console.error('Couldn\'t add items to gravity container.');
          }
          return storage(implementationCount).box2DHolder.add(data);
        }
      };
      if (methods[methodOrOptions]) {
        return methods[methodOrOptions].apply(this, Array.prototype.slice.call(arguments, 1));
      } else if (typeof methodOrOptions === 'object' || !methodOrOptions) {
        return methods.init.apply(this, arguments);
      } else {
        console.error("Method " + method + " does not exist on $.RadialGravity");
      }
      return this;
    }
  });
})(this.jQuery || this.Zepto, this);
