// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var Calendar;

  Calendar = app.module();
  Calendar.Views.UpcomingContainer = Backbone.View.extend({
    tagName: 'ul',
    id: 'upcoming-calendar-container',
    beforeRender: function() {
      var model, modelArray, _i, _len, _results;

      modelArray = this.collection.where({
        IsUpcoming: true
      });
      if (modelArray) {
        _results = [];
        for (_i = 0, _len = modelArray.length; _i < _len; _i++) {
          model = modelArray[_i];
          _results.push(this.insertView('', new Calendar.Views.UpcomingListItem({
            model: model
          })));
        }
        return _results;
      }
    }
  });
  Calendar.Views.UpcomingListItem = Backbone.View.extend({
    tagName: 'li',
    className: 'upcoming-calendar-list-item',
    template: 'upcoming-calendar-list-item',
    serialize: function() {
      if (this.model) {
        return this.model.toJSON();
      } else {
        return {};
      }
    }
  });
  Calendar.Views.Detail = Backbone.View.extend({
    tagName: 'article',
    className: 'portfolio-detail',
    template: 'calendar-detail',
    afterRender: function() {
      return window.picturefill();
    },
    serialize: function() {
      if (this.model) {
        return this.model.toJSON();
      } else {
        return {};
      }
    }
  });
  return Calendar;
});
