// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var CalendarEntry;

  CalendarEntry = app.module();
  JJRestApi.Modules.extend('CalendarEntry', function(CalendarEntry) {
    JJRestApi.extendModel('CalendarEntry', {
      foo: 'bar'
    });
    return JJRestApi.extendCollection('CalendarEntry', {
      foo: 'bar'
    });
  });
  return CalendarEntry;
});
