// Generated by CoffeeScript 1.6.3
define(['app'], function(app, Gravity, Portfolio) {
  var DocImage;
  DocImage = app.module();
  return JJRestApi.Modules.extend('DocImage', function(DocImage) {
    JJRestApi.extendModel('DocImage', {
      /**
      			 * used for Image markdown parser to determine if the member may see this image or not
      			 * @return {boolean}
      */

      isVisibleForMember: function() {
        var isVisible,
          _this = this;
        isVisible = false;
        _.each(['Projects', 'Workshops', 'Exhibitions', 'Excursions'], function(type) {
          if (_this.get(type).findWhere({
            EditableByMember: true
          })) {
            return isVisible = true;
          }
        });
        return isVisible;
      }
    });
    return JJRestApi.extendCollection('DocImage', {
      foo: 'bar'
    });
  });
});
