// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var Editor;

  Editor = app.module();
  Editor.Views.NewProject = Backbone.View.extend({
    tagName: 'div',
    template: 'security/create-project',
    events: {
      'submit form.create-project': 'createNewProject',
      'click .project-type-list a': 'setProjectType'
    },
    setProjectType: function(e) {
      var type;

      e.preventDefault();
      type = $(e.currentTarget).data('type');
      if (type) {
        this.projectType = type;
      }
      return false;
    },
    createNewProject: function(e) {
      var errorMsg, m, model, person, title;

      e.preventDefault();
      title = $(e.target).find('[name="title"]').val();
      errorMsg = null;
      if (!title) {
        errorMsg = 'Please fill in a title!';
      }
      if (!this.projectType) {
        errorMsg = 'Please choose the type of your project!';
      }
      if (errorMsg) {
        this.showMessageAt(errorMsg, this.$el, 'error');
      } else {
        if (person = app.CurrentMemberPerson) {
          m = JJRestApi.Model(this.projectType);
          model = new m({
            Title: title,
            Persons: person
          });
          model.save(null, {
            success: function() {
              model._isCompletelyFetched = true;
              model._isFetchedWhenLoggedIn = true;
              return Backbone.history.navigate('/secured/edit/' + model.get('UglyHash') + '/', true);
            }
          });
        }
      }
      return false;
    }
  });
  return Editor;
});
