// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var Editor;

  Editor = app.module();
  Editor.Views.NewProject = Backbone.View.extend({
    tagName: 'div',
    template: 'security/create-project',
    events: {
      'submit form.create-project': 'createNewProject',
      'click .project-type-list a': 'setProjectType'
    },
    setProjectType: function(e) {
      var type;

      e.preventDefault();
      type = $(e.currentTarget).data('type');
      if (type) {
        this.projectType = type;
      }
      return false;
    },
    createNewProject: function(e) {
      var title;

      e.preventDefault();
      title = $(e.target).find('[name="title"]').val();
      return false;
    }
  });
  return Editor;
});
