// Generated by CoffeeScript 1.4.0

define(["app"], function(app) {
  var Example;
  Example = app.module();
  Example.Model = Backbone.Model.extend({});
  Example.Collection = Backbone.Collection.extend({});
  Example.Router = Backbone.Router.extend({});
  Example.Views.Head = Backbone.View.extend({
    template: 'head',
    tagName: 'div',
    className: 'head'
  });
  return Example;
});
