// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var Excursion;

  Excursion = app.module();
  JJRestApi.Modules.extend('Excursion', function(Excursion) {
    JJRestApi.extendModel('Excursion', {
      foo: 'bar'
    });
    return JJRestApi.extendCollection('Excursion', {
      foo: 'bar'
    });
  });
  return Excursion;
});
