// Generated by CoffeeScript 1.6.2
define(['app', 'modules/SuperProject'], function(app, SuperProject) {
  var Excursion;

  Excursion = app.module();
  JJRestApi.Modules.extend('Excursion', function(Excursion) {
    JJRestApi.extendModel('Excursion', SuperProject.Model, {
      foo: 'bar'
    });
    return JJRestApi.extendCollection('Excursion', {
      foo: 'bar'
    });
  });
  return Excursion;
});
