// Generated by CoffeeScript 1.6.2
define(['app', 'modules/SuperProject'], function(app, SuperProject) {
  var Exhibition;

  Exhibition = app.module();
  JJRestApi.Modules.extend('Exhibition', function(Exhibition) {
    JJRestApi.extendModel('Exhibition', SuperProject.Model, {
      foo: 'bar'
    });
    return JJRestApi.extendCollection('Exhibition', {
      foo: 'bar'
    });
  });
  return Exhibition;
});
