// Generated by CoffeeScript 1.6.2
define(['app', 'modules/Gravity', 'modules/Portfolio'], function(app, Gravity, Portfolio) {
  var Person;

  Person = app.module();
  JJRestApi.Modules.extend('Person', function(Person) {
    JJRestApi.extendModel('Person', {
      /**
      				 * @return {String} either 'student' or 'alumni' or 'employee'
      */

      getLinkingSlug: function() {
        if (this.get('IsEmployee')) {
          return 'employee';
        }
        if (this.get('IsStudent')) {
          return 'student';
        }
        if (this.get('IsAlumni')) {
          return 'alumni';
        }
        return '';
      }
    });
    return JJRestApi.extendCollection('Person', {
      foo: 'bar'
    });
  });
  Person.Views.GravityContainer = Gravity.Views.Container.extend({
    tagName: 'ul',
    className: 'gravity',
    beforeRender: function() {
      var model, modelArray, projectType, rel, rels, _i, _j, _k, _len, _len1, _len2, _ref, _results;

      console.log('render person page with normal view');
      modelArray = [];
      rels = this.model.relations;
      _ref = app.Config.ProjectTypes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        projectType = _ref[_i];
        for (_j = 0, _len1 = rels.length; _j < _len1; _j++) {
          rel = rels[_j];
          if (rel.collectionType === projectType) {
            modelArray = modelArray.concat(this.model.get(rel.key).models);
          }
        }
      }
      _results = [];
      for (_k = 0, _len2 = modelArray.length; _k < _len2; _k++) {
        model = modelArray[_k];
        _results.push(this.insertView('', new Portfolio.Views.ListItem({
          model: model,
          linkTo: 'about'
        })));
      }
      return _results;
    }
  });
  Person.Views.CustomView = Backbone.View.extend({});
  return Person;
});
