// Generated by CoffeeScript 1.6.2
define(['app', 'plugins/zepto.gravity'], function(app) {
  var Portfolio;

  Portfolio = app.module();
  Portfolio.Views.GravityContainer = Backbone.View.extend({
    tagName: 'ul',
    id: 'gravity-container',
    className: 'gravity',
    beforeRender: function() {
      var model, modelArray, _i, _len, _results;

      console.log('portfolio before render');
      modelArray = this.collection;
      if (modelArray) {
        _results = [];
        for (_i = 0, _len = modelArray.length; _i < _len; _i++) {
          model = modelArray[_i];
          _results.push(this.insertView('', new Portfolio.Views.ListItem({
            model: model
          })));
        }
        return _results;
      }
    },
    afterRender: function() {
      /*
      				$(@.el).height($(window).height()).RadialGravity 
      					worker:
      						physics: '/app/assets/js/plugins/gravity/physics.js'
      */

    }
  });
  Portfolio.Views.ListItem = Backbone.View.extend({
    tagName: 'li',
    className: 'gravity-item',
    template: 'gravity-list-item',
    serialize: function() {
      if (this.model) {
        return this.model.toJSON();
      } else {
        return {};
      }
    }
  });
  return Portfolio;
});
