// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var Project;

  Project = app.module();
  JJRestApi.Modules.extend(Project, function(Project) {
    JJRestApi.extendModel('Project', {
      sayHello: function() {
        return console.log('I am a project model');
      }
    });
    JJRestApi.extendCollection('Project', {
      sayHello: function() {
        return console.log('I am a project collection');
      }
    });
    return Project.Views.Test = Backbone.View.extend({
      template: 'head',
      tagName: 'div',
      className: 'head'
    });
  });
  return Project;
});
