// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var Project;

  Project = app.module();
  JJRestApi.Modules.extend(Project, function(Project) {
    return JJRestApi.extendModel('Project', JJRestApi.extendCollection('Project', Project.Views.Test = Backbone.View.extend({
      template: 'head',
      tagName: 'div',
      className: 'head'
    })));
  });
  return Project;
});
