// Generated by CoffeeScript 1.6.2
define(['app', 'modules/RecycleBin'], function(app, RecycleBin) {
  "use strict";
  var Website;

  Website = app.module();
  Website.Views.ListView = Backbone.View.extend({
    tagName: 'li',
    template: 'website-list-item',
    className: 'Website',
    serialize: function() {
      return {
        ID: this.model.id,
        Title: this.model.get('Title'),
        Link: this.model.get('Link')
      };
    },
    afterRender: function() {
      return RecycleBin.setViewAsRecyclable(this);
    }
  });
  return Website;
});
