// Generated by CoffeeScript 1.6.2
define(['app'], function(app) {
  var Workshop;

  Workshop = app.module();
  JJRestApi.Modules.extend('Workshop', function(Workshop) {
    JJRestApi.extendModel('Workshop', {
      foo: 'bar'
    });
    return JJRestApi.extendCollection('Workshop', {
      foo: 'bar'
    });
  });
  return Workshop;
});
