// Generated by CoffeeScript 1.6.2
define(['app', 'modules/SuperProject'], function(app, SuperProject) {
  var Workshop;

  Workshop = app.module();
  JJRestApi.Modules.extend('Workshop', function(Workshop) {
    JJRestApi.extendModel('Workshop', SuperProject.Model, {
      foo: 'bar'
    });
    return JJRestApi.extendCollection('Workshop', {
      foo: 'bar'
    });
  });
  return Workshop;
});
