// Generated by CoffeeScript 1.6.2
"use strict";(function($) {
  var $editorSidebar, $imageList, $sidebarContent, $sidebarHeader, closeSidebar, columnsPrefix, getColumnsCount, onResizeSidebar, openSidebar, setColumnCount, setSidebarHeight, toggleSidebar;

  $.fn.call = function(callback) {
    if (callback) {
      return callback();
    }
  };
  $editorSidebar = $('.editor-sidebar');
  $sidebarHeader = $('> header', $editorSidebar);
  $sidebarContent = $('section.editor-sidebar-content', $editorSidebar);
  columnsPrefix = 'columns-';
  openSidebar = function() {
    $editorSidebar.addClass('open');
    return setTimeout(setColumnCount, 300);
  };
  getColumnsCount = function() {
    return $editorSidebar.data('columns');
  };
  closeSidebar = function() {
    var prefColumnsCount;

    prefColumnsCount = getColumnsCount();
    $editorSidebar.removeClass('open');
    return setTimeout(function() {
      return $editorSidebar.removeClass(columnsPrefix + prefColumnsCount);
    }, 300);
  };
  toggleSidebar = function() {
    if ($editorSidebar.hasClass('open')) {
      return closeSidebar();
    } else {
      return openSidebar();
    }
  };
  setSidebarHeight = function() {
    return $sidebarContent.css({
      'height': $(window).height() - $sidebarHeader.outerHeight()
    });
  };
  setColumnCount = function() {
    var columnsCount, prefColumnsCount, width;

    width = parseInt($sidebarContent.width(), 10);
    prefColumnsCount = getColumnsCount();
    columnsCount = Math.floor(width / 75);
    if (columnsCount) {
      return $editorSidebar.removeClass(columnsPrefix + prefColumnsCount).addClass(columnsPrefix + columnsCount).data('columns', columnsCount);
    }
  };
  onResizeSidebar = function() {
    setSidebarHeight();
    return setColumnCount();
  };
  $('#show-editor-sidebar').on('click', function() {
    return toggleSidebar();
  });
  $imageList = $('.image-list', $editorSidebar);
  if ($imageList.length) {
    $('a', $imageList).on('click', function() {
      $('.selected', $imageList).not(this).removeClass('selected');
      return $(this).toggleClass('selected');
    });
    false;
  }
  $.addOnWindowResize('editor.sidebar.height', onResizeSidebar);
  setSidebarHeight();
  setColumnCount();
  return this;
})(jQuery);
