// Generated by CoffeeScript 1.6.2
"use strict";(function($) {
  var $container, $packeryEl, $sizing, $window, onResize, packery, resizeTimeout;

  $window = $(window);
  $container = $('.packery-wrapper');
  $sizing = $('.packery-test', $container);
  $packeryEl = $('.packery', $container);
  resizeTimeout = null;
  onResize = function() {
    var elHeight, newHeight;

    newHeight = $window.height();
    $container.height(newHeight);
    $packeryEl.width(Math.floor($container.width() / 3) * 2);
    packery.layout();
    elHeight = $packeryEl.height();
    if (elHeight < newHeight) {
      return $packeryEl.css('top', Math.floor((newHeight - elHeight) / 2));
    } else {
      return $packeryEl.css('top', 0);
    }
  };
  packery = new Packery($packeryEl[0], {
    containerStyle: null,
    itemSelector: '.packery-item',
    gutter: 0,
    stamped: '.stamp',
    isResizeBound: false
  });
  $window.on('resize', function() {
    if (resizeTimeout) {
      clearTimeout(resizeTimeout);
    }
    return resizeTimeout = setTimeout(onResize, 100);
  });
  return onResize();
})(jQuery);
