---
Name: nm
After: 'framework/*', 'cms/*'
---
SSViewer:
  theme: 'nm'
Member:
  extensions:
    - 'MemberPersonExtension'
    - 'MemberProjectTypesExtension'


---
Name: ResponsiveImage
---
ResponsiveImage:
  wrapper_tag: 'span'
  image_tag: 'span'
  extensions:
    - 'ResponsiveImageCaptionExtension'
    - 'ResponsiveImageUrlExtension'


---
Name: Admin
---
SecurityAdmin:
  menu_icon: 'foo'
  menu_priority: 39
GDBackend:
  default_quality: 95
DateField:
  showcalendar: true
LeftAndMain:
  extensions:
    - 'LeftAndMainExtension'


---
Name: JJRestApi
---
Structure_RestApiExtension:
  add:
    - 'Person'
  ignore:
    - 'Member'
    - 'Ranking'
    - 'Group'
    - 'Permission'
    - 'PermissionRole'
    - 'PermissionRoleCode'
    - 'ResponsiveImage'
    - 'ResponsiveImageObject'
    - 'File'
CSRFProtection_RestApiExtension:
  enabled_for:
    - 'POST'
    - 'PUT'
    - 'DELETE'
    - 'PATCH'

---
Name: StaticUrls
---
SubdomainAssetsConfig:
  domain_name: 'nm.local'
  subdomain_points_to_assets: false