---
Name: nm
After: 'framework/*', 'cms/*'
---
SSViewer:
  theme: 'nm'
Member:
  extensions:
    - 'MemberPersonExtension'
---
Name: ResponsiveImage
---
ResponsiveImage:
  WrapperTag: 'span'
  ImageTag: 'span'
  extensions:
    - 'ResponsiveImageCaptionExtension'
    - 'ResponsiveImageUrlExtension'
---
Name: Admin
---
SecurityAdmin:
  menu_icon: 'foo'
  menu_priority: 39
GDBackend:
  default_quality: 95
DateField:
  showcalendar: true
LeftAndMain:
  extensions:
    - 'LeftAndMainExtension'
---
Name: JJRestApi
---
Structure_RestApiExtension:
  add:
    - 'Person'
  ignore:
    - 'Member'
    - 'Ranking'
    - 'Group'
    - 'Permission'
    - 'PermissionRole'
    - 'PermissionRoleCode'
    - 'ResponsiveImage'
    - 'ResponsiveImageObject'
    - 'File'
CSRFProtection_RestApiExtension:
  enable_for:
    - 'POST'
    - 'PUT'
    - 'DELETE'
    - 'PATCH'