---
Name: approutes
Before:
  - 'jjrestapi/routes#apiroutes'
---
Director:
  rules:
    'admin': 'AdminRootController'
    'dev': 'DevelopmentAdmin'
    'Security//$Action/$ID/$OtherID': 'Security'
    '$Action/$OtherAction/$ID/$OtherID': 'RootURLController'
---
Name: apiextraroutes
After:
  - 'jjrestapi/routes#apiroutes'
---
Director:
  rules:
    'api/v2/Auth': 'Authentication_RestApiController'