---
Name: approutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'admin': 'AdminRootController'
    'dev': 'DevelopmentAdmin'
    'Security//$Action/$ID/$OtherID': 'Security'
    '$Action/$OtherAction/$ID/$OtherID': 'RootURLController'
---
Name: apiroutes
After: jjrestapi/routes#coreroutes
---
Director:
  rules:
    'api/v2/Auth': 'Authentication_RestApiController'